config/routes.rb
Rails.application.routes.draw do
  get 'users/show'
  
  resources :hospitals
  devise_for :users
  resources :users
  get 'welcome/index'

  resources :patients do
  	resources :referrals
  	end
 root to: 'welcome#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/hospital.rb
class Hospital < ApplicationRecord
	has_many :referrals
end

app/models/patient.rb
class Patient < ApplicationRecord
	belongs_to :user
	has_many :referrals	
end

app/models/patient_search.rb
class PatientSearch
	attr_reader :date_from, :date_to

	def initialize(params)
		params ||= {}
		@date_from = parsed_date(params[:date_from], 7.days.ago.to_date.to_s)
		@date_to = parsed_date(params[:date_to], Date.today.to_s)

	end

	def scope 
		Patient.where('date BETWEEN ? AND ?', @date_from, date_to)
	end

	private 
	def parsed_date(date_string, default)
		Date.parse(date_string)
	rescue ArgumentError, TypeError
		default
	end
end

app/models/referral.rb
class Referral < ApplicationRecord
	belongs_to :patient
	belongs_to :user
	belongs_to :hospital
end

app/models/user.rb
class User < ApplicationRecord
	has_many :patients
	has_many :referrals
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

end

app/controllers/hospitals_controller.rb
class HospitalsController < ApplicationController
  before_action :set_hospital, only: [:show, :edit, :update, :destroy]

  # GET /hospitals
  # GET /hospitals.json
  def index
    @hospitals = Hospital.all
  end

  # GET /hospitals/1
  # GET /hospitals/1.json
  def show
  end

  # GET /hospitals/new
  def new
    @hospital = Hospital.new
  end

  # GET /hospitals/1/edit
  def edit
  end

  # POST /hospitals
  # POST /hospitals.json
  def create
    @hospital = Hospital.new(hospital_params)

    respond_to do |format|
      if @hospital.save
        format.html { redirect_to @hospital, notice: 'Hospital was successfully created.' }
        format.json { render :show, status: :created, location: @hospital }
      else
        format.html { render :new }
        format.json { render json: @hospital.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /hospitals/1
  # PATCH/PUT /hospitals/1.json
  def update
    respond_to do |format|
      if @hospital.update(hospital_params)
        format.html { redirect_to @hospital, notice: 'Hospital was successfully updated.' }
        format.json { render :show, status: :ok, location: @hospital }
      else
        format.html { render :edit }
        format.json { render json: @hospital.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /hospitals/1
  # DELETE /hospitals/1.json
  def destroy
    @hospital.destroy
    respond_to do |format|
      format.html { redirect_to hospitals_url, notice: 'Hospital was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_hospital
      @hospital = Hospital.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def hospital_params
      params.require(:hospital).permit(:name, :address, :doctor, :department)
    end
end

app/controllers/patients_controller.rb
class PatientsController < ApplicationController
  before_action :set_patient, only: [:show, :edit, :update, :destroy]

  # GET /patients
  # GET /patients.json
  def index
    @search = PatientSearch.new(params[:search])
    @patients = @search.scope
  end

  # GET /patients/1
  # GET /patients/1.json
  def show
  end

  # GET /patients/new
  def new
    #@patient = Patient.new
    @patient = current_user.patients.build
  end

  # GET /patients/1/edit
  def edit
  end

  # POST /patients
  # POST /patients.json
  def create
    @patient = current_user.patients.build(patient_params)

    respond_to do |format|
      if @patient.save
        format.html { redirect_to @patient, notice: 'Patient was successfully created.' }
        format.json { render :show, status: :created, location: @patient }
      else
        format.html { render :new }
        format.json { render json: @patient.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /patients/1
  # PATCH/PUT /patients/1.json
  def update
    respond_to do |format|
      if @patient.update(patient_params)
        format.html { redirect_to @patient, notice: 'Patient was successfully updated.' }
        format.json { render :show, status: :ok, location: @patient }
      else
        format.html { render :edit }
        format.json { render json: @patient.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /patients/1
  # DELETE /patients/1.json
  def destroy
    @patient.destroy
    respond_to do |format|
      format.html { redirect_to patients_url, notice: 'Patient was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_patient
      @patient = Patient.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def patient_params
      params.require(:patient).permit(:name, :dob, :address, :phone, :date, :infection, :injury, :observations)
    end
end

app/controllers/referrals_controller.rb
class ReferralsController < ApplicationController
	before_action :find_patient
	before_action :find_referral, only: [:destroy]

  def new
    @referral = current_user.referrals.build
    @hospitals = Hospital.all.map{ |h| [h.name, h.id]}
  end

  def create
    @referral = current_user.referrals.build(referral_params)
    @referral.patient_id = @patient.id
    @referral.user_id = current_user.id
    @referral.hospital_id = params[:hospital_id]

    if @referral.save
      redirect_to patient_path(@patient)

    else
      render 'new'
    end
  end

  def destroy
     	@referral.destroy
     	redirect_to patient_path(@patient)
  end

  private
  def referral_params
    params.required(:referral).permit(:name, :address, :dob, :phone, :consultation, :hospital_id)
  end

  def find_patient
    @patient = Patient.find(params[:patient_id])
  end

  def find_referral
      @referral = Referral.find(params[:id])
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
  	@user = User.find(params[:id])
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/hospitals_helper.rb
module HospitalsHelper
end

app/helpers/patients_helper.rb
module PatientsHelper
end

app/helpers/referrals_helper.rb
module ReferralsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/hospitals/_form.html.erb
<%= form_for(hospital) do |f| %>
  <% if hospital.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(hospital.errors.count, "error") %> prohibited this hospital from being saved:</h2>

      <ul>
      <% hospital.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :address %>
    <%= f.text_area :address %>
  </div>

  <div class="field">
    <%= f.label :doctor %>
    <%= f.text_field :doctor %>
  </div>

  <div class="field">
    <%= f.label :department %>
    <%= f.text_area :department %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/hospitals/edit.html.erb
<h1>Editing Hospital</h1>

<%= render 'form', hospital: @hospital %>

<%= link_to 'Show', @hospital %> |
<%= link_to 'Back', hospitals_path %>

app/views/hospitals/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Hospitals</h1>

<div class="media">
  <div class="media-body">
    <table class="table table-hover">
      <thead>
        <tr>
          <th>Name</th>
          <th>Address</th>
          <th>Doctor</th>
          <th>Department</th>
          <th colspan="3"></th>
        </tr>
      </thead>

      <tbody>
        <% @hospitals.each do |hospital| %>
          <tr>
            <td><%= hospital.name %></td>
            <td><%= hospital.address %></td>
            <td><%= hospital.doctor %></td>
            <td><%= hospital.department %></td>
            <td><%= link_to 'Show', hospital %></td>
            <td><%= link_to 'Edit', edit_hospital_path(hospital) %></td>
            <td><%= link_to 'Destroy', hospital, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>
<br>

<%= link_to 'Add New Hospital', new_hospital_path %>

app/views/hospitals/new.html.erb
<h1>New Hospital</h1>

<%= render 'form', hospital: @hospital %>

<%= link_to 'Back', hospitals_path %>

app/views/hospitals/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @hospital.name %>
</p>

<p>
  <strong>Address:</strong>
  <%= @hospital.address %>
</p>

<p>
  <strong>Doctor:</strong>
  <%= @hospital.doctor %>
</p>

<p>
  <strong>Department:</strong>
  <%= @hospital.department %>
</p>

<%= link_to 'Edit', edit_hospital_path(@hospital) %> |
<%= link_to 'Back', hospitals_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SmartClinic</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
<nav class="navbar navbar-default">
<div class="container">
		<ul class="nav nav-tabs">
		  <li><%= link_to "Smart-Clinic@NCI", root_path, class: "navbar-brand" %></li>
		 
		  <ul class="nav navbar-nav navbar-right ">
			
			<% if user_signed_in? %>
				
				<li><%= link_to "Patients", patients_path %></li>
		  		<li><%= link_to "Hospitals", hospitals_path %></li>
				<li><%= link_to 'Add New Patient', new_patient_path %>
			<% end %>

			<% if current_user %>
			  <li><%= link_to "Sign Out", destroy_user_session_path, method: :delete %></li>
			<% else %>
				<li><%= link_to "Sign Up", new_user_registration_path %></li>
				<li><%= link_to "Log In", new_user_session_path %></li>
			<% end %>
		  </ul>
  		</ul>

		<% if flash[:notice] %>
			<div class="alert alert-success">
				<button type="button" class="close" data-dismiss="alert">&times;</button>
					<%= flash[:notice] %>
			</div>
		<% elsif flash[:error] %>
			<div class="alert alert-error">
				<button type="button" class="close" data-dismiss="alert">&times;</button>
					<%= flash[:error] %>
			</div>
		<% elsif flash[:alert] %>
			<div class="alert">
				<button type="button" class="close" data-dismiss="alert">&times;</button>
				<%= flash[:alert] %>
			</div>
		  <% end %>
      
      </div>
      </nav>

      <div class="container">
    <%= yield %>
</div>
    </body>
  </html>

app/views/patients/_form.html.erb
<div class="row">
  <%= form_for patient, html: {class: 'form-horizontal'} do |f| %>
    <% if patient.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(patient.errors.count, "error") %> prohibited this patient from being saved:</h2>

        <ul>
        <% patient.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

    <div class="control-group">
        <%= f.label :name, class: 'control-label' %><br>
      <div class="controls">
        <%= f.text_field :name %>
      </div>
    </div>

    <div class="control-group">
        <%= f.label :dob, class: 'control-label' %><br>
      <div class="controls">
        <%= f.date_field :dob %>
      </div>
    </div>

    <div class="control-group">
        <%= f.label :address, class: 'control-label' %><br>
      <div class="controls">
        <%= f.text_area :address %>
      </div>
    </div>

    <div class="control-group">
        <%= f.label :phone, class: 'control-label' %><br>
      <div class="controls">
        <%= f.text_field :phone %>
      </div>
    </div>

    <div class="control-group">
        <%= f.label :date, class: 'control-label' %><br>
      <div class="controls">
        <%= f.text_field :date %>
      </div>
    </div>

    <div class="control-group">
        <%= f.label :infection, class: 'control-label' %><br>
      <div class="controls">
        <%= f.text_area :infection %>
      </div>
    </div>

    <div class="control-group">
        <%= f.label :injury, class: 'control-label' %><br>
      <div class="controls">
        <%= f.text_area :injury %>
      </div>
    </div>

    <div class="control-group">
        <%= f.label :observations, class: 'control-label' %><br>
      <div class="controls">
        <%= f.text_area :observations %>
      </div>
    </div>

    <div class="control-group">
      <div class="controls">
        <%= f.submit %>
      </div>
    </div>
  <% end %>
</div>

app/views/patients/edit.html.erb
<h1>Editing Patient</h1>

<%= render 'form', patient: @patient %>

<%= link_to 'Show', @patient %> |
<%= link_to 'Back', patients_path %>

app/views/patients/index.html.erb
<div class="row">
<h1>Listing Patients</h1>
<div class="pull-right range-query">
    <%= form_tag patients_path, method: :get do %>
      <%= text_field_tag 'search[date_from]', @search.date_from %>
      <%= text_field_tag 'search[date_to]', @search.date_to %>
      <%= submit_tag 'Search', class: 'btn search-button' %>
    <% end %>
  </div>
</div>

<div class="media">
  <div class="media-body">
    <table class="table table-hover">
      <thead>
        <tr>
          <th>Name</th>
          <th>Dob</th>
          <th>Address</th>
          <th>Phone</th>
          <th>Date</th>
          <th>Infection</th>
          <th>Injury</th>
          <th>Observations</th>
          <th colspan="3"></th>
        </tr>
      </thead>

      <tbody>
        <% @patients.each do |patient| %>
          <tr>
            <td><%= patient.name %></td>
            <td><%= patient.dob %></td>
            <td><%= patient.address %></td>
            <td><%= patient.phone %></td>
            <td><%= patient.date %></td>
            <td><%= patient.infection %></td>
            <td><%= patient.injury %></td>
            <td><%= patient.observations %></td>
            <td><%= link_to 'Show', patient, class: 'btn btn-mini' %></td>
            <td><%= link_to 'Edit', edit_patient_path(patient), class: 'btn btn-mini btn-success' %></td>
            <td><%= link_to 'Destroy', patient, method: :delete, class: 'btn btn-mini btn-danger', data: { confirm: 'Are you sure?' } %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>
<br>

<%= link_to 'Add New Patient', new_patient_path, class: 'btn btn-mini btn-success' %>

app/views/patients/new.html.erb
<h1>New Patient</h1>

<%= render 'form', patient: @patient %>

<%= link_to 'Back', patients_path %>

app/views/patients/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @patient.name %>
</p>

<p>
  <strong>Dob:</strong>
  <%= @patient.dob %>
</p>

<p>
  <strong>Address:</strong>
  <%= @patient.address %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @patient.phone %>
</p>

<p>
  <strong>Date:</strong>
  <%= @patient.date %>
</p>

<p>
  <strong>Infection:</strong>
  <%= @patient.infection %>
</p>

<p>
  <strong>Injury:</strong>
  <%= @patient.injury %>
</p>

<p>
  <strong>Observations:</strong>
  <%= @patient.observations %>
</p>

<div>
  <%= link_to 'Add Referral', new_patient_referral_path(@patient), class: 'btn btn-mini btn-success' %>
</div>

<%= link_to 'Edit', edit_patient_path(@patient) %> |
<%= link_to 'Back', patients_path %>

app/views/referrals/_form.html.erb
<%= form_for([@patient, @patient.referrals.build]) do |f| %>

  <%= select_tag(:hospital_id, options_for_select(@hospitals), :prompt => "Select a hospital") %>

	<div class="control-group">
        <%= f.label :name, class: 'control-label' %><br>
      <div class="controls">
        <%= f.text_field :name %>
      </div>
    </div>

    <div class="control-group">
        <%= f.label :address, class: 'control-label' %><br>
      <div class="controls">
        <%= f.text_area :address %>
      </div>
    </div>

	<div class="control-group">
        <%= f.label :dob, class: 'control-label' %><br>
      <div class="controls">
        <%= f.date_field :dob %>
      </div>
    </div>
 
    <div class="control-group">
        <%= f.label :phone, class: 'control-label' %><br>
      <div class="controls">
        <%= f.text_field :phone %>
      </div>
    </div>
  
 	<div class="control-group">
        <%= f.label :consultation, class: 'control-label' %><br>
      <div class="controls">
        <%= f.text_area :consultation %>
      </div>
    </div>
  
 	<div class="control-group">
      <div class="controls">
        <%= f.submit %>
      </div>
    </div>

 
<% end %>

app/views/referrals/_referral.html.erb

<p><%= referral.name %></p>
<p><%= referral.address %></p>
<p><%= referral.dob %></p>
<p><%= referral.phone %></p>
<p><%= referral.consultation %></p>

<%= link_to "Delete", patient_referral_path(referral.patient, referral), 
method: :delete, data: {confirm: "Are you sure?"} %>

app/views/referrals/index.html.erb
<h1>List the referrals</h1>
  <%= render @patient.referrals %>

app/views/referrals/new.html.erb
<h1>New Referral</h1>

<%= render 'form' %>

app/views/users/show.html.erb
<h1>User Profile</h1>

<h3>User Name: <%= @user.email %></h3>
<h3>Time Signed In: <%= @user.current_sign_in_at %></h3>
<h3>Last Time Signed In: <%= @user.last_sign_in_at %></h3>

app/views/welcome/about.html.erb
<h1>Welcome#about</h1>
<p>Find me in app/views/welcome/about.html.erb</p>

app/views/welcome/contact.html.erb
<h1>Welcome#contact</h1>
<p>Find me in app/views/welcome/contact.html.erb</p>

app/views/welcome/faq.html.erb
<h1>Welcome#faq</h1>
<p>Find me in app/views/welcome/faq.html.erb</p>

app/views/welcome/features.html.erb
<h1>Welcome#features</h1>
<p>Find me in app/views/welcome/features.html.erb</p>

app/views/welcome/index.html.erb
<div id="main">
<h1>Welcome To Smart-Clinic@NCI</h1>
</div>

<div id="footer">
<hr>
<p>
Copyright 
<%= "#{start_year} - " if defined? start_year %>
<%= Date.today.year %> 
Maricel@https://smart-clinic-nci.herokuapp.com
</p>
</div>

app/views/welcome/pricing.html.erb
<h1>Welcome#pricing</h1>
<p>Find me in app/views/welcome/pricing.html.erb</p>